version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: RedisServerDockerfile
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - alden
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: OllamaServerDockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama/models
    networks:
      - alden
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  alden-core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_CUDA: "true"
    container_name: alden-core
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:////app/data/webui.db
      - ENABLE_AUTH0=True
      - AUTH0_DOMAIN=${AUTH0_DOMAIN:-auth.example.com}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_API_IDENTIFIER=${AUTH0_API_IDENTIFIER}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - OLLAMA_BASE_URLS=http://ollama:11434
    volumes:
      - ./data:/app/data
    networks:
      - alden
    depends_on:
      - redis
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  redis-data:
  ollama-models:

networks:
  alden:
    external: true 